"""
Django settings for mybestpal project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '6yb24@v7mz(q43we=*a0go2n22h1jpy7*o%#zj2+d$!d9xz3lz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['localhost', '127.0.0.1',"mybestpal.herokuapp.com"]


# Application definition

INSTALLED_APPS = [
    'bootstrap3',
    'rest_framework',
    'login_signup.apps.LoginSignUpConfig',
    'firstlook.apps.FirstlookConfig',
    'mytask.apps.MytaskConfig',
    'games.apps.GamesConfig',
    'game2048.apps.Game2048Config',
    'gametictactoe.apps.GametictactoeConfig',
    'main.apps.MainConfig',




    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mybestpal.urls'


#'DIRS': ["C:/summer_apps/final_mybestpal_v2/mybestpal/gametictactoe/template/","C:/summer_apps/final_mybestpal_v2/mybestpal/game2048/template/","C:/summer_apps/final_mybestpal_v2/mybestpal/games/template/","C:/summer_apps/final_mybestpal_v2/mybestpal/mytask/template/","C:/summer_apps/final_mybestpal_v2/mybestpal/firstlook/template/","C:/summer_apps/final_mybestpal_v2/mybestpal/login_signup/template/","C:/summer_apps/final_mybestpal_v2/mybestpal/login_signup/views/Login_v1/Login_v1/",],
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':[os.path.join(BASE_DIR, 'gametictactoe/template/'),BASE_DIR,os.path.join(BASE_DIR, 'game2048/template/'),os.path.join(BASE_DIR, 'games/template/'),os.path.join(BASE_DIR, 'mytask/template/'),os.path.join(BASE_DIR, 'firstlook/template/'),os.path.join(BASE_DIR, 'login_signup/template/'),os.path.join(BASE_DIR, 'login_signup/views/Login_v1/Login_v1/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mybestpal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases


DATABASES = {
        'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mybestpalV3',
        'HOST': 'localhost',
        'USER': "root",
        'PASSWORD': "mysql"
        }
    }


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

#
import dj_database_url
db_from_env = dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(db_from_env)


# mysql://b905d83450da86:c6a86722@us-cdbr-iron-east-04.cleardb.net/heroku_28634ab26747abb?reconnect=true

# DATABASES['default'] = {
#     'ENGINE': 'django.db.backends.mysql',
#     'HOST': 'us-cdbr-iron-east-04.cleardb.net',
#     'USER': 'b905d83450da86',
#     'NAME': 'heroku_28634ab26747abb',
#     'PASSWORD': 'c6a86722',
#     'OPTIONS': {'ssl': {'ca': '/path/to/cert.pem', 'cert': '/path/to/cert.pem', 'key': '/path/to/key.pem'}, },
# }
#



STATIC_URL = '/static/'
#STATIC_ROOT = "/static/"


#INTERNAL_IPS=["127.0.0.1"]

STATICFILES_DIRS = [

    os.path.join(BASE_DIR, "static/login_signup/"),
    os.path.join(BASE_DIR, "static/first_look/"),
    os.path.join(BASE_DIR, "static/games/"),
    os.path.join(BASE_DIR, "static/game2048/"),
    os.path.join(BASE_DIR, "static"),

]


STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'